/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.conexao;



/**
 *
 * @author emanu
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFusuario = new javax.swing.JTextField();
        TFsenha = new javax.swing.JTextField();
        botaoLOGIN = new javax.swing.JButton();
        butaoREGISTRO = new javax.swing.JButton();
        Labelusu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 153));

        TFusuario.setBackground(new java.awt.Color(255, 255, 255));
        TFusuario.setForeground(new java.awt.Color(255, 153, 153));
        TFusuario.setText("Digite seu usuario");
        TFusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFusuarioFocusLost(evt);
            }
        });
        TFusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFusuarioActionPerformed(evt);
            }
        });

        TFsenha.setBackground(new java.awt.Color(255, 255, 255));
        TFsenha.setForeground(new java.awt.Color(255, 153, 153));
        TFsenha.setText("Exemplo: Denner24@gmail.com");
        TFsenha.setCaretColor(new java.awt.Color(204, 204, 204));
        TFsenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFsenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFsenhaFocusLost(evt);
            }
        });
        TFsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsenhaActionPerformed(evt);
            }
        });

        botaoLOGIN.setBackground(new java.awt.Color(255, 255, 255));
        botaoLOGIN.setForeground(new java.awt.Color(0, 0, 0));
        botaoLOGIN.setText("Login");

        butaoREGISTRO.setBackground(new java.awt.Color(255, 255, 255));
        butaoREGISTRO.setForeground(new java.awt.Color(0, 0, 0));
        butaoREGISTRO.setText("Registrar");
        butaoREGISTRO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                butaoREGISTROFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                butaoREGISTROFocusLost(evt);
            }
        });
        butaoREGISTRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoREGISTROMouseClicked(evt);
            }
        });
        butaoREGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoREGISTROActionPerformed(evt);
            }
        });

        Labelusu.setText("Usuario");

        jLabel1.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butaoREGISTRO, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(botaoLOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Labelusu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TFusuario)
                        .addComponent(TFsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(Labelusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(botaoLOGIN)
                .addGap(18, 18, 18)
                .addComponent(butaoREGISTRO)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFusuarioActionPerformed
       
    }//GEN-LAST:event_TFusuarioActionPerformed

    private void TFusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFusuarioFocusGained
     if (TFusuario.getText().equals("Digite seu usuario")) {
        TFusuario.setText(""); // Limpa o campo ao ganhar foco se estiver com o texto padrão
    }
    }//GEN-LAST:event_TFusuarioFocusGained

    private void TFusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFusuarioFocusLost
    if (TFusuario.getText().trim().isEmpty()) {
        TFusuario.setText("Digite seu usuario"); // Recoloca o texto padrão apenas se o campo estiver vazio
    }
    }//GEN-LAST:event_TFusuarioFocusLost

    private void butaoREGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoREGISTROActionPerformed
TelaRegistro telaRegistro = new TelaRegistro();
    telaRegistro.setVisible(true);    
    }//GEN-LAST:event_butaoREGISTROActionPerformed

    private void butaoREGISTROFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_butaoREGISTROFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoREGISTROFocusGained

    private void butaoREGISTROFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_butaoREGISTROFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoREGISTROFocusLost

    private void butaoREGISTROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoREGISTROMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoREGISTROMouseClicked

    private void TFsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsenhaActionPerformed

    private void TFsenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFsenhaFocusLost
        if (TFsenha.getText().trim().isEmpty()) {
            TFsenha.setText("Exemplo: Denner24@gmail.com"); // Recoloca o texto padrão apenas se o campo estiver vazio
        }
    }//GEN-LAST:event_TFsenhaFocusLost

    private void TFsenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFsenhaFocusGained
        if (TFsenha.getText().equals("Exemplo: Denner24@gmail.com")) {
            TFsenha.setText(""); // Limpa o campo ao ganhar foco se estiver com o texto padrão
        }
    }//GEN-LAST:event_TFsenhaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelusu;
    private javax.swing.JTextField TFsenha;
    private javax.swing.JTextField TFusuario;
    private javax.swing.JButton botaoLOGIN;
    private javax.swing.JButton butaoREGISTRO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
